# Generated by Django 3.0.4 on 2020-04-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('bjj_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='like',
            field=models.ManyToManyField(related_name='liked', to='login_app.User'),
        ),
    ]
